version: '3.4'
services:
  db:
    image: mongo:latest
    ports:
      - '27017:27017'

  rest-api-node:
    build: ./backend
    ports:
      - '8000:8000'
    links:
      - db
    restart: on-failure

  client:
    build: ./frontend
    ports: 
      - '80:80'
      - '443:443'